development:
  adapter: postgresql
  encoding: unicode
  database: recipe-group-app
  pool: 5
  host: localhost
  username: dannybenshi
  password: DannyPro123

test:
  adapter: postgresql
  encoding: unicode
  database: recipe-group-app-test
  pool: 5
  username: dannybenshi
  password: DannyPro123

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 

