development:
  adapter: postgresql
  encoding: unicode
  database: recipe-group-app
  pool: 5
  host: localhost
  username: post
  password: annor0543

test:
  adapter: postgresql
  encoding: unicode
  database: recipe-group-app-test
  pool: 5
  username: recipe-app
  password: annor0543

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 

